# ================== DATABASE ==================
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/clinic_management?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
quarkus.datasource.jdbc.initial-size=5
quarkus.datasource.jdbc.max-size=20

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# ================== SERVER ==================
quarkus.http.port=8080

# ================== SWAGGER ==================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.info-title=API Clinic management
quarkus.smallrye-openapi.info-version=1.0.0

quarkus.log.category."io.smallrye.jwt".level=TRACE
quarkus.log.category."org.jboss.resteasy.reactive".level=DEBUG


# ================== JWT RSA CONFIGURATION ==================
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://clinic-management.com

# ================== LOGGING CONFIGURATION ==================
quarkus.log.level=INFO
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."org.jboss.resteasy.reactive.common.core.UncaughtExceptionMapper".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n