quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
quarkus.datasource.jdbc.initial-size=5
quarkus.datasource.jdbc.max-size=20

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.database.generation.strategy=update

quarkus.http.port=8080


quarkus.swagger-ui.always-include=true
quarkus.index-dependency.swagger-ui.enabled=true
quarkus.smallrye-openapi.info-title=API Clinic management
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.path=/swagger